### ISSUE TITLE
Wiki Home Page - Due 6/9

### ISSUE THREAD

**Issue by cjc473** [vincentpham123/mumblr#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a description sentence of the app
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

**Comment by cjc473** [comment]
Almost complete - see empty checkboxes above.

**Comment by vincentpham123** [comment]
1. I have added a placeholder for my live link
2. I have included a description for my app/

**Comment by cjc473** [comment]
Done!
