### ISSUE TITLE
Database Schema - Due 6/9

### ISSUE THREAD

**Issue by cjc473** [vincentpham123/mumblr#3]
# Database Schema

- [x] Contains correct datatypes
- [ ] Contains appropriate constraints/details (primary and foreign keys, not null, indexed, unique)
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] table names, column names, and foreign keys are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded

**Comment by cjc473** [comment]
This is almost complete!

1. Fix formatting for Comments Table name.
2. Mention that Direct Messages is a bonus table, or remove it for now.
3. Remove image_url from the Posts table. We'll be referencing images using active storage in a separate part of our database (more to come on this once you start setting up AWS).

**Comment by vincentpham123** [comment]
1. I have updated the formatting for the comments table
2.  I have include a note that direct messages will be a bonus feature
3. Image_url has been removed from the posts table

**Comment by cjc473** [comment]
Done!

**Comment by cjc473** [comment]
I noticed one last change to make when I was reviewing sample state. In your comments table, you have a comment_id column. Is this supposed to be for parent comments? If so, go ahead and rename this parent_comment_id.

**Comment by vincentpham123** [comment]
Hi Chris, I went back on Tumblr and saw that there ar eno parent comments. I will go ahead and remove it from my comments table

**Comment by cjc473** [comment]
Done!
