### ISSUE TITLE
Sample State - Due 6/12

### ISSUE THREAD

**Issue by cjc473** [vincentpham123/mumblr#4]
# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + The author username and imageurl for a post. Basically any info that the user can't change
        + Like count and a boolean on whether the user likes the post instead of a likes slice

**Comment by cjc473** [comment]
Remaining changes:

1. In posts slice, change body column to content.
2. Move the reblogs and comments slice inside of entities.
3. In comments slice, rename commentId if necessary (see final note on schema issue page).
4. Add errors slice of state. The authenticate me project will walk you through adding errors from your session state, and it's actually really useful!
5. Add a ui slice of state. This handles loading screens and modals. Since tumblr has a login modal, you'll want to include that here. See the bluebird sample state formatting for reference.
6. Make all snake_case columns camelCase.

**Comment by vincentpham123** [comment]
1. updated all state keys to camelCased
2.  Moved reblogs and comments into entities
3. removed commentId for now. Tumblr does not have replies to comments
4. added an errors slice of state, it currently has a comment for invlaid usernames or passwords
5. added ann UI slice of state
6. makde all columns camelCase

**Comment by cjc473** [comment]
Done!
