### ISSUE TITLE
Backend Routes - Due 6/13

### ISSUE THREAD

**Issue by cjc473** [vincentpham123/mumblr#5]
# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

**Comment by cjc473** [comment]
Changes:

1. Fix formatting on API Endpoints
2. Add GET route for session (this is used in our auth pattern toward the end of authenticate me)
3. Make Post and Delete all caps in the Follows and Likes sections

**Comment by vincentpham123** [comment]
Implemented the changes

**Comment by cjc473** [comment]
Done!
