### ISSUE TITLE
Frontend Routes - Due 6/13

### ISSUE THREAD

**Issue by cjc473** [vincentpham123/mumblr#6]
# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by cjc473** [comment]
There are a couple snake_case routes here - change them to camelCase and this will be done.

**Comment by vincentpham123** [comment]
I changed the routes that were snake_cased to camelCase

**Comment by cjc473** [comment]
Done!
